import type { LedgerDocument } from './domain';

/** Single-tenant fixture: NZ Akahu + AU CDR (consent expiring) + manual property. */
export const MOCK_LEDGER: LedgerDocument = {
  connections: [
    {
      id: 'conn-akahu-anz',
      provider: 'akahu',
      country: 'NZ',
      institution_name: 'ANZ',
      status: 'active',
      scopes: 'read_only',
      last_synced_at: '2026-09-16T02:00:00.000Z',
      consent_expires_at: null,
    },
    {
      id: 'conn-aucdr-cba',
      provider: 'basiq',
      country: 'AU',
      institution_name: 'Commonwealth Bank',
      status: 'consent_expiring',
      scopes: 'read_only',
      last_synced_at: '2026-09-10T04:00:00.000Z',
      consent_expires_at: '2026-09-30T00:00:00.000Z',
    },
    {
      id: 'conn-manual',
      provider: 'manual',
      country: 'NZ',
      institution_name: 'Manual ledger',
      status: 'active',
      scopes: 'read_only',
      last_synced_at: '2026-09-16T02:00:00.000Z',
      consent_expires_at: null,
    },
    {
      id: 'conn-csv-ks',
      provider: 'csv',
      country: 'NZ',
      institution_name: 'KiwiSaver (CSV)',
      status: 'active',
      scopes: 'read_only',
      last_synced_at: '2026-09-01T00:00:00.000Z',
      consent_expires_at: null,
    },
  ],
  accounts: [
    {
      id: 'acc-anz-everyday',
      connection_id: 'conn-akahu-anz',
      country: 'NZ',
      type: 'cash',
      name: 'ANZ Everyday',
      institution: 'ANZ',
      currency: 'NZD',
      current_balance: 18420,
      available_balance: 18420,
    },
    {
      id: 'acc-anz-mortgage',
      connection_id: 'conn-akahu-anz',
      country: 'NZ',
      type: 'mortgage',
      name: 'Home loan',
      institution: 'ANZ',
      currency: 'NZD',
      current_balance: 412000,
      available_balance: null,
    },
    {
      id: 'acc-cba-card',
      connection_id: 'conn-aucdr-cba',
      country: 'AU',
      type: 'credit_card',
      name: 'CBA Awards',
      institution: 'Commonwealth Bank',
      currency: 'AUD',
      current_balance: 2140,
      available_balance: 12860,
    },
    {
      id: 'acc-sharesies',
      connection_id: 'conn-manual',
      country: 'NZ',
      type: 'investment',
      name: 'Sharesies',
      institution: 'Sharesies',
      currency: 'NZD',
      current_balance: 24680,
      available_balance: 24680,
    },
    {
      id: 'acc-kiwisaver',
      connection_id: 'conn-csv-ks',
      country: 'NZ',
      type: 'kiwi_saver',
      name: 'Simplicity Growth (CSV)',
      institution: 'Simplicity',
      currency: 'NZD',
      current_balance: 86200,
      available_balance: 86200,
    },
  ],
  holdings: [
    {
      id: 'hld-vti',
      account_id: 'acc-sharesies',
      ticker_or_name: 'VTI',
      asset_class: 'fund',
      units: 42,
      price: 290,
      market_value: 12180,
      cost_basis: 9800,
      currency: 'NZD',
    },
    {
      id: 'hld-nzx',
      account_id: 'acc-sharesies',
      ticker_or_name: 'FPH.NZ',
      asset_class: 'equity',
      units: 80,
      price: 156.25,
      market_value: 12500,
      cost_basis: 11000,
      currency: 'NZD',
    },
  ],
  properties: [
    {
      id: 'prop-grey-lynn',
      country: 'NZ',
      address: 'Grey Lynn, Auckland',
      estimated_value: 1180000,
      currency: 'NZD',
      valuation_source: 'manual',
      mortgage_account_id: 'acc-anz-mortgage',
    },
  ],
  manualAssets: [
    {
      id: 'ma-car',
      name: 'Car',
      country: 'NZ',
      value: 18000,
      currency: 'NZD',
    },
  ],
  manualLiabilities: [],
};
